services:
  app:
    build: .
    container_name: websrv-app
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/service?sslmode=disable
      - DATABASE_MAX_CONNS=25
      - DATABASE_MIN_CONNS=5
      - DATABASE_MAX_CONN_LIFE_TIME=30m
      - DATABASE_MAX_CONN_IDLE_TIME=5m
      - DATABASE_HEALTH_CHECK_PERIOD=1m
      - APP_URL=:8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - service

  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - service
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - service
    restart: unless-stopped

volumes:
  pgdata:


networks:
  service:
    driver: bridge
    name: service
